credentials:
  usernames:
    Crossfit83:
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: 
      password: 
cookie:  
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
